# Generated by Django 5.0.6 on 2024-05-27 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_task_delete_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='created_date',
            new_name='date',
        ),
    ]
